import {
  IconNumber123,
  IconAdOff,
  IconHeartFilled,
  IconUser,
  IconHome,
  IconBrandGoogle,
  IconTool,
  IconTrophy,
  IconClipboardText,
  IconLogout,
  IconBook,
  IconBriefcase2,
  IconBulb,
  IconCash,
  IconHeart,
  IconQuestionMark,
  IconTrashFilled,
  IconTrash,
  IconApple,
  IconBarbell,
  IconBath,
  IconBike,
  IconBriefcase,
  IconCar,
  IconCoffee,
  IconDeviceLaptop,
  IconDroplet,
  IconGasStation,
  IconGlassFull,
  IconMoodNeutral,
  IconMoodSad,
  IconMoodSmile,
  IconPaw,
  IconPill,
  IconRun,
  IconShoppingCart,
  IconStretching,
  IconUsers,
  IconVideo,
  IconWriting,
  IconZzz,
  IconToolsKitchen3,
  IconPlus,
  IconDatabase,
} from 'angular-tabler-icons/icons';

export const COMMON_ICONS = {
  IconNumber123,
  IconAdOff,
  IconHeartFilled,
  IconUser,
  IconHome,
  IconBrandGoogle,
  IconTool,
  IconTrophy,
  IconClipboardText,
  IconLogout,
  IconTrash,
  IconDatabase,

  //
  IconQuestionMark,
  IconBriefcase2,
  IconBulb,
  IconCash,
  IconHeart,
  IconBook,
  IconPlus,

  // Salute
  IconBath,
  IconDroplet,
  IconPill,
  IconZzz,
  // Sport
  IconBarbell,
  IconRun,
  IconStretching,
  // Cibo
  IconToolsKitchen3,
  IconCoffee,
  IconApple,
  IconGlassFull,
  // Trasporti
  IconCar,
  IconGasStation,
  IconBike,
  // Lavoro
  IconBriefcase,
  IconDeviceLaptop,
  IconVideo,
  IconWriting,
  // Mood
  IconMoodSmile,
  IconMoodNeutral,
  IconMoodSad,
  // Casa/Social
  IconPaw,
  IconUsers,
  IconShoppingCart,
};
