import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./types`.

export type UserMetadata = Models.Row & {
    content: string;
    userId: string;
}
