import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./types`.

export type UserMetadata = Models.Row & {
  categoriesJson: string;
  tagsJson: string;
};
export type SimpleEntry = Models.Row & {
  tagIdList: string[] | null;
  content: string;
  date: string;
  categoryId: string;
};

export type TaskItem = Models.Row & {
  title: string;
  description: string | null;
  isCompleted: boolean;
  track: boolean;
  categoryId: string | null;
  tagIdList: string[] | null;
};
